// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GooglePlayServicesConstants
{
        public const string leaderboard_hungry_shark_global_leaderboard = "CgkInJiYwPwaEAIQAQ"; // <GPGSID>
        public const string achievement_high_score = "CgkInJiYwPwaEAIQCQ"; // <GPGSID>
        public const string achievement_arctic_high_score = "CgkInJiYwPwaEAIQBg"; // <GPGSID>
        public const string achievement_calamari = "CgkInJiYwPwaEAIQDg"; // <GPGSID>
        public const string leaderboard_hungry_shark_arctic_ocean_leaderboard = "CgkInJiYwPwaEAIQAw"; // <GPGSID>
        public const string achievement_mutated = "CgkInJiYwPwaEAIQEw"; // <GPGSID>
        public const string leaderboard_hungry_shark_arabian_sea_leaderboard = "CgkInJiYwPwaEAIQBA"; // <GPGSID>
        public const string achievement_gold_digger = "CgkInJiYwPwaEAIQFQ"; // <GPGSID>
        public const string achievement_archers_score = "CgkInJiYwPwaEAIQCw"; // <GPGSID>
        public const string achievement_survival_instinct = "CgkInJiYwPwaEAIQFw"; // <GPGSID>
        public const string achievement_theres_allways_a_bigger_fish = "CgkInJiYwPwaEAIQFA"; // <GPGSID>
        public const string achievement_marathon_shark = "CgkInJiYwPwaEAIQDA"; // <GPGSID>
        public const string achievement_good_score = "CgkInJiYwPwaEAIQCA"; // <GPGSID>
        public const string achievement_red_ocean = "CgkInJiYwPwaEAIQDQ"; // <GPGSID>
        public const string achievement_super_score = "CgkInJiYwPwaEAIQCg"; // <GPGSID>
        public const string achievement_empty_sea = "CgkInJiYwPwaEAIQEA"; // <GPGSID>
        public const string achievement_born_survivor = "CgkInJiYwPwaEAIQGA"; // <GPGSID>
        public const string achievement_arabian_sea_high_score = "CgkInJiYwPwaEAIQBw"; // <GPGSID>
        public const string achievement_pacific_high_score = "CgkInJiYwPwaEAIQBQ"; // <GPGSID>
        public const string achievement_mega_rush = "CgkInJiYwPwaEAIQFg"; // <GPGSID>
        public const string leaderboard_hungry_shark_pacific_islands_leaderboard = "CgkInJiYwPwaEAIQAg"; // <GPGSID>
        public const string achievement_tastes_better_than_it_looks = "CgkInJiYwPwaEAIQEQ"; // <GPGSID>
        public const string achievement_tasty_feet = "CgkInJiYwPwaEAIQEg"; // <GPGSID>
        public const string achievement_archenemy = "CgkInJiYwPwaEAIQDw"; // <GPGSID>

}

